port: "8000"
db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  dbname: "postgres"
  sslmode: "disable"
aiApi:
  model: "google/gemini-2.0-flash-lite-preview-02-05:free"
  key: "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"
  address: "https://openrouter.ai/api/v1/chat/completions"
